// Automatically generated by generate_photos_js.py
// Edit the title values after generation if you want custom captions.

const galleryData = [
    {
        category: "Foyer",
        file: "images/Foyer/Foyer-1.jpg",
        width: 480,
        height: 360,
        title: "Foyer 1"
    },
    {
        category: "Foyer",
        file: "images/Foyer/Foyer-2.jpg",
        width: 360,
        height: 480,
        title: "Foyer 2"
    },
    {
        category: "Foyer",
        file: "images/Foyer/Foyer-3.jpg",
        width: 360,
        height: 480,
        title: "Foyer 3"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/Second_Floor_Shared-1.jpg",
        width: 360,
        height: 480,
        title: "Second Floor Shared 1"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/Second_Floor_Shared-2.jpg",
        width: 360,
        height: 480,
        title: "Second Floor Shared 2"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/Second_Floor_Shared-3.jpg",
        width: 480,
        height: 360,
        title: "Second Floor Shared 3"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/Second_Floor_Shared-4.jpg",
        width: 360,
        height: 480,
        title: "Second Floor Shared 4"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/laundry-1.jpg",
        width: 360,
        height: 480,
        title: "Laundry 1"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/laundry-2.jpg",
        width: 360,
        height: 480,
        title: "Laundry 2"
    },
    {
        category: "Second Floor Shared",
        file: "images/Second_Floor_Shared/second-floor-hall-closet.jpg",
        width: 360,
        height: 480,
        title: "Second Floor Hall Closet"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-1.jpg",
        width: 360,
        height: 480,
        title: "Backyard 1"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-2.jpg",
        width: 480,
        height: 360,
        title: "Backyard 2"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-3.jpg",
        width: 480,
        height: 360,
        title: "Backyard 3"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-4.jpg",
        width: 480,
        height: 360,
        title: "Backyard 4"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-5.jpg",
        width: 480,
        height: 360,
        title: "Backyard 5"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-6.jpg",
        width: 480,
        height: 360,
        title: "Backyard 6"
    },
    {
        category: "Backyard",
        file: "images/backyard/backyard-7.jpg",
        width: 480,
        height: 360,
        title: "Backyard 7"
    },
    {
        category: "Basement",
        file: "images/basement/basement-1.jpg",
        width: 480,
        height: 360,
        title: "Basement 1"
    },
    {
        category: "Basement",
        file: "images/basement/basement-2.jpg",
        width: 480,
        height: 360,
        title: "Basement 2"
    },
    {
        category: "Basement",
        file: "images/basement/basement-3.jpg",
        width: 480,
        height: 360,
        title: "Basement 3"
    },
    {
        category: "Basement",
        file: "images/basement/basement-4.jpg",
        width: 480,
        height: 360,
        title: "Basement 4"
    },
    {
        category: "Bathrooms",
        file: "images/bathrooms/First_Floor_Half_Bath.jpg",
        width: 360,
        height: 480,
        title: "First Floor Half Bath"
    },
    {
        category: "Bathrooms",
        file: "images/bathrooms/Owner's_Suite_Bath-1.jpg",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 1"
    },
    {
        category: "Bathrooms",
        file: "images/bathrooms/Owner's_Suite_Bath-2.jpg",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 2"
    },
    {
        category: "Bathrooms",
        file: "images/bathrooms/Owner's_Suite_Bath-3.jpg",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 3"
    },
    {
        category: "Bathrooms",
        file: "images/bathrooms/Owner's_Suite_Bath-4.jpg",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 4"
    },
    {
        category: "Bathrooms",
        file: "images/bathrooms/Second_Floor_Bath-2.jpg",
        width: 360,
        height: 480,
        title: "Second Floor Bath 2"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/Owner's_Suite-1.jpg",
        width: 360,
        height: 480,
        title: "Owner'S Suite 1"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/Owner's_Suite-2.jpg",
        width: 360,
        height: 480,
        title: "Owner'S Suite 2"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/Owner's_Suite-3.jpg",
        width: 480,
        height: 360,
        title: "Owner'S Suite 3"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/Owner's_Suite-4.jpg",
        width: 480,
        height: 360,
        title: "Owner'S Suite 4"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/Walk-in-closet.jpg",
        width: 480,
        height: 360,
        title: "Walk In Closet"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_2-1.jpg",
        width: 360,
        height: 480,
        title: "Bedroom 2 1"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_2-2.jpg",
        width: 360,
        height: 480,
        title: "Bedroom 2 2"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_2-3.jpg",
        width: 480,
        height: 360,
        title: "Bedroom 2 3"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_2-4.jpg",
        width: 480,
        height: 360,
        title: "Bedroom 2 4"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_3-1.jpg",
        width: 360,
        height: 480,
        title: "Bedroom 3 1"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_3-2.jpg",
        width: 360,
        height: 480,
        title: "Bedroom 3 2"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_3-3.jpg",
        width: 360,
        height: 480,
        title: "Bedroom 3 3"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_3-4.jpg",
        width: 480,
        height: 360,
        title: "Bedroom 3 4"
    },
    {
        category: "Bedrooms",
        file: "images/bedrooms/bedroom_3-5.jpg",
        width: 480,
        height: 360,
        title: "Bedroom 3 5"
    },
    {
        category: "Deck",
        file: "images/deck/deck-1.jpg",
        width: 480,
        height: 360,
        title: "Deck 1"
    },
    {
        category: "Deck",
        file: "images/deck/deck-2.jpg",
        width: 480,
        height: 360,
        title: "Deck 2"
    },
    {
        category: "Deck",
        file: "images/deck/deck-3.jpg",
        width: 480,
        height: 360,
        title: "Deck 3"
    },
    {
        category: "Deck",
        file: "images/deck/deck-4.jpg",
        width: 480,
        height: 360,
        title: "Deck 4"
    },
    {
        category: "Exterior",
        file: "images/exterior/Back_of_house-2.jpg",
        width: 360,
        height: 480,
        title: "Back Of House 2"
    },
    {
        category: "Exterior",
        file: "images/exterior/Front-1.jpg",
        width: 480,
        height: 360,
        title: "Front 1"
    },
    {
        category: "Exterior",
        file: "images/exterior/Front-2.jpg",
        width: 480,
        height: 360,
        title: "Front 2"
    },
    {
        category: "Exterior",
        file: "images/exterior/Front_Corner.jpg",
        width: 360,
        height: 480,
        title: "Front Corner"
    },
    {
        category: "Exterior",
        file: "images/exterior/back_of_house-1.jpg",
        width: 360,
        height: 480,
        title: "Back Of House 1"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/garage_entry.jpg",
        width: 360,
        height: 480,
        title: "Garage Entry"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-1.jpg",
        width: 480,
        height: 360,
        title: "Kitchen 1"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-2.jpg",
        width: 480,
        height: 360,
        title: "Kitchen 2"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-3.jpg",
        width: 480,
        height: 360,
        title: "Kitchen 3"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-4.jpg",
        width: 480,
        height: 360,
        title: "Kitchen 4"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-5.jpg",
        width: 360,
        height: 480,
        title: "Kitchen 5"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-6.jpg",
        width: 360,
        height: 480,
        title: "Kitchen 6"
    },
    {
        category: "Kitchen",
        file: "images/kitchen/kitchen-7.jpg",
        width: 480,
        height: 360,
        title: "Kitchen 7"
    },
    {
        category: "Living",
        file: "images/living/Great_Room-1.jpg",
        width: 480,
        height: 360,
        title: "Great Room 1"
    },
    {
        category: "Living",
        file: "images/living/Great_Room-2.jpg",
        width: 480,
        height: 360,
        title: "Great Room 2"
    },
    {
        category: "Living",
        file: "images/living/Great_Room-3.jpg",
        width: 480,
        height: 360,
        title: "Great Room 3"
    },
    {
        category: "Living",
        file: "images/living/Great_Room_4.jpg",
        width: 480,
        height: 360,
        title: "Great Room 4"
    },
    {
        category: "Neighborhood",
        file: "images/neighborhood/neighborhood-1.jpg",
        width: 480,
        height: 360,
        title: "Neighborhood 1"
    }
];
