// Automatically generated by generate_photos_js.py
// Gallery files point to optimized WebP images in images/web/.
// Edit title values after generation if you want custom captions.

const galleryData = [
    {
        category: "Foyer",
        file: "images/web/Foyer/Foyer-1.webp",
        width: 480,
        height: 360,
        title: "Foyer 1"
    },
    {
        category: "Foyer",
        file: "images/web/Foyer/Foyer-2.webp",
        width: 360,
        height: 480,
        title: "Foyer 2"
    },
    {
        category: "Foyer",
        file: "images/web/Foyer/Foyer-3.webp",
        width: 360,
        height: 480,
        title: "Foyer 3"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/Second_Floor_Shared-1.webp",
        width: 360,
        height: 480,
        title: "Second Floor Shared 1"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/Second_Floor_Shared-2.webp",
        width: 360,
        height: 480,
        title: "Second Floor Shared 2"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/Second_Floor_Shared-3.webp",
        width: 480,
        height: 360,
        title: "Second Floor Shared 3"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/Second_Floor_Shared-4.webp",
        width: 360,
        height: 480,
        title: "Second Floor Shared 4"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/laundry-1.webp",
        width: 360,
        height: 480,
        title: "Laundry 1"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/laundry-2.webp",
        width: 360,
        height: 480,
        title: "Laundry 2"
    },
    {
        category: "Second Floor Shared",
        file: "images/web/Second_Floor_Shared/second-floor-hall-closet.webp",
        width: 360,
        height: 480,
        title: "Second Floor Hall Closet"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-1.webp",
        width: 360,
        height: 480,
        title: "Backyard 1"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-2.webp",
        width: 480,
        height: 360,
        title: "Backyard 2"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-3.webp",
        width: 480,
        height: 360,
        title: "Backyard 3"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-4.webp",
        width: 480,
        height: 360,
        title: "Backyard 4"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-5.webp",
        width: 480,
        height: 360,
        title: "Backyard 5"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-6.webp",
        width: 480,
        height: 360,
        title: "Backyard 6"
    },
    {
        category: "Backyard",
        file: "images/web/backyard/backyard-7.webp",
        width: 480,
        height: 360,
        title: "Backyard 7"
    },
    {
        category: "Basement",
        file: "images/web/basement/basement-1.webp",
        width: 480,
        height: 360,
        title: "Basement 1"
    },
    {
        category: "Basement",
        file: "images/web/basement/basement-2.webp",
        width: 480,
        height: 360,
        title: "Basement 2"
    },
    {
        category: "Basement",
        file: "images/web/basement/basement-3.webp",
        width: 480,
        height: 360,
        title: "Basement 3"
    },
    {
        category: "Basement",
        file: "images/web/basement/basement-4.webp",
        width: 480,
        height: 360,
        title: "Basement 4"
    },
    {
        category: "Bathrooms",
        file: "images/web/bathrooms/First_Floor_Half_Bath.webp",
        width: 360,
        height: 480,
        title: "First Floor Half Bath"
    },
    {
        category: "Bathrooms",
        file: "images/web/bathrooms/Owner's_Suite_Bath-1.webp",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 1"
    },
    {
        category: "Bathrooms",
        file: "images/web/bathrooms/Owner's_Suite_Bath-2.webp",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 2"
    },
    {
        category: "Bathrooms",
        file: "images/web/bathrooms/Owner's_Suite_Bath-3.webp",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 3"
    },
    {
        category: "Bathrooms",
        file: "images/web/bathrooms/Owner's_Suite_Bath-4.webp",
        width: 360,
        height: 480,
        title: "Owner'S Suite Bath 4"
    },
    {
        category: "Bathrooms",
        file: "images/web/bathrooms/Second_Floor_Bath-2.webp",
        width: 360,
        height: 480,
        title: "Second Floor Bath 2"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/Owner's_Suite-1.webp",
        width: 360,
        height: 480,
        title: "Owner'S Suite 1"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/Owner's_Suite-2.webp",
        width: 360,
        height: 480,
        title: "Owner'S Suite 2"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/Owner's_Suite-3.webp",
        width: 480,
        height: 360,
        title: "Owner'S Suite 3"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/Owner's_Suite-4.webp",
        width: 480,
        height: 360,
        title: "Owner'S Suite 4"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/Walk-in-closet.webp",
        width: 480,
        height: 360,
        title: "Walk In Closet"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_2-1.webp",
        width: 360,
        height: 480,
        title: "Bedroom 2 1"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_2-2.webp",
        width: 360,
        height: 480,
        title: "Bedroom 2 2"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_2-3.webp",
        width: 480,
        height: 360,
        title: "Bedroom 2 3"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_2-4.webp",
        width: 480,
        height: 360,
        title: "Bedroom 2 4"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_3-1.webp",
        width: 360,
        height: 480,
        title: "Bedroom 3 1"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_3-2.webp",
        width: 360,
        height: 480,
        title: "Bedroom 3 2"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_3-3.webp",
        width: 360,
        height: 480,
        title: "Bedroom 3 3"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_3-4.webp",
        width: 480,
        height: 360,
        title: "Bedroom 3 4"
    },
    {
        category: "Bedrooms",
        file: "images/web/bedrooms/bedroom_3-5.webp",
        width: 480,
        height: 360,
        title: "Bedroom 3 5"
    },
    {
        category: "Deck",
        file: "images/web/deck/deck-1.webp",
        width: 480,
        height: 360,
        title: "Deck 1"
    },
    {
        category: "Deck",
        file: "images/web/deck/deck-2.webp",
        width: 480,
        height: 360,
        title: "Deck 2"
    },
    {
        category: "Deck",
        file: "images/web/deck/deck-3.webp",
        width: 480,
        height: 360,
        title: "Deck 3"
    },
    {
        category: "Deck",
        file: "images/web/deck/deck-4.webp",
        width: 480,
        height: 360,
        title: "Deck 4"
    },
    {
        category: "Exterior",
        file: "images/web/exterior/Back_of_house-2.webp",
        width: 360,
        height: 480,
        title: "Back Of House 2"
    },
    {
        category: "Exterior",
        file: "images/web/exterior/Front-1.webp",
        width: 480,
        height: 360,
        title: "Front 1"
    },
    {
        category: "Exterior",
        file: "images/web/exterior/Front-2.webp",
        width: 480,
        height: 360,
        title: "Front 2"
    },
    {
        category: "Exterior",
        file: "images/web/exterior/Front_Corner.webp",
        width: 360,
        height: 480,
        title: "Front Corner"
    },
    {
        category: "Exterior",
        file: "images/web/exterior/back_of_house-1.webp",
        width: 360,
        height: 480,
        title: "Back Of House 1"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/garage_entry.webp",
        width: 360,
        height: 480,
        title: "Garage Entry"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-1.webp",
        width: 480,
        height: 360,
        title: "Kitchen 1"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-2.webp",
        width: 480,
        height: 360,
        title: "Kitchen 2"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-3.webp",
        width: 480,
        height: 360,
        title: "Kitchen 3"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-4.webp",
        width: 480,
        height: 360,
        title: "Kitchen 4"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-5.webp",
        width: 360,
        height: 480,
        title: "Kitchen 5"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-6.webp",
        width: 360,
        height: 480,
        title: "Kitchen 6"
    },
    {
        category: "Kitchen",
        file: "images/web/kitchen/kitchen-7.webp",
        width: 480,
        height: 360,
        title: "Kitchen 7"
    },
    {
        category: "Living",
        file: "images/web/living/Great_Room-1.webp",
        width: 480,
        height: 360,
        title: "Great Room 1"
    },
    {
        category: "Living",
        file: "images/web/living/Great_Room-2.webp",
        width: 480,
        height: 360,
        title: "Great Room 2"
    },
    {
        category: "Living",
        file: "images/web/living/Great_Room-3.webp",
        width: 480,
        height: 360,
        title: "Great Room 3"
    },
    {
        category: "Living",
        file: "images/web/living/Great_Room_4.webp",
        width: 480,
        height: 360,
        title: "Great Room 4"
    },
    {
        category: "Neighborhood",
        file: "images/web/neighborhood/neighborhood-1.webp",
        width: 480,
        height: 360,
        title: "Neighborhood 1"
    }
];
